server:
  port: 8081
  servlet:
    path: /f
spring:
  application:
    name: fast
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_mall?seUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.ytq.fast.security1.entity
  configuration:
    use-actual-param-name: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  secretKey: abc
  expiration: 600
  tokenHeader: Authorization #JWT存储的请求头
  tokenHead: Bearer  #JWT负载中拿到开头