auth-server-url: http://localhost:8089 # 授权服务地址
server:
  port: 8089
security:
  oauth2:
    client:
      client-id: test
      client-secret: test01
      scope: all
      registered-redirect-uri: http://mrbird.cc
      access-token-uri: ${auth-server-url}/oauth/token
      user-authorization-uri: ${auth-server-url}/oauth/authorize
    resource:
      token-info-uri: ${auth-server-url}/oauth/check_token #检查令牌