package com.kunchi.spring.model;

public class ss {

    /**
     * Project
     * getRootProject
     * getRootDir
     * getBuildDir
     * setBuildDir
     * setBuildDir
     * getBuildFile
     * getParent
     * getName
     * getDisplayName
     * getDescription
     * setDescription
     * getGroup
     * setGroup
     * getVersion
     * setVersion
     * getStatus
     * setStatus
     * getChildProjects
     * setProperty
     * getProject
     * getAllprojects
     * getSubprojects
     * task
     * task
     * task
     * task
     * getPath
     * getDefaultTasks
     * setDefaultTasks
     * defaultTasks
     * evaluationDependsOn
     * evaluationDependsOnChildren
     * findProject
     * project
     * project
     * project
     * getAllTasks
     * getTasksByName
     * getProjectDir
     * file
     * file
     * uri
     * relativePath
     * files
     * files
     * files
     * fileTree
     * fileTree
     * fileTree
     * fileTree
     * zipTree
     * tarTree
     * provider
     * property
     * getProviders
     * getObjects
     * getLayout
     * mkdir
     * delete
     * delete
     * javaexec
     * javaexec
     * exec
     * exec
     * absoluteProjectPath
     * relativeProjectPath
     * getAnt
     * createAntBuilder
     * ant
     * ant
     * getConfigurations
     * configurations
     * getArtifacts
     * artifacts
     * artifacts
     * getConvention
     * depthCompare
     * getDepth
     * getTasks
     * subprojects
     * subprojects
     * allprojects
     * allprojects
     * beforeEvaluate
     * afterEvaluate
     * beforeEvaluate
     * afterEvaluate
     * hasProperty
     * getProperties
     * property
     * findProperty
     * getLogger
     * getGradle
     * getLogging
     * configure
     * configure
     * configure
     * getRepositories
     * repositories
     * getDependencies
     * dependencies
     * getBuildscript
     * buildscript
     * copy
     * copy
     * copySpec
     * copySpec
     * copySpec
     * sync
     * getState
     * container
     * container
     * container
     * getExtensions
     * getResources
     * getComponents
     * getNormalization
     * normalization
     * DEFAULT_BUILD_FILE
     * PATH_SEPARATOR
     * DEFAULT_BUILD_DIR_NAME
     * GRADLE_PROPERTIES
     * SYSTEM_PROP_PREFIX
     * DEFAULT_VERSION
     * DEFAULT_STATUS
     */

}
